### ISSUE TITLE
Getting comment and wrong Ruby

### ISSUE THREAD

**Issue by MtnBiker** [MikeMcQuaid/Linter.tmbundle#1]
`Linting streets_controller.rb with Ruby 2.0.0p648, RuboCop
sh: : command not found`

Probably not really an issue with Linter, but my TM setup. But thought I'd bug you first. I'm using `ruby 2.4.1p111` via ch-ruby.

**Comment by MikeMcQuaid** [comment]
Setup your `PATH` variable in your `.tm_properties` to ensure that your desired `ruby` is found first in your `PATH`.
